### ISSUE TITLE
docker images do not include latest changes

### ISSUE THREAD

**Issue by proud-nerd** [wishthis/docker#5]
# Description
According to [Docker Hub](https://hub.docker.com/r/hiob/wishthis/tags) all images are from 11 days ago (04.10.2023). But the image with the `release-candidate` tag does not include all changes up to this date. 

# Expected behavior
When pulling a tagged image I expect it to include all of the latest changes up to that date

# Actual behavior
The `release-candidate` image pushed on the 04.10.2023 only includes changes made till (roughly) 24.09.2023 (quickly scanning through [the commits on the release-candidate branch](https://github.com/wishthis/wishthis/commits/release-candidate) and comparing those to the actual files inside of my container

**Comment by Hiobi** [comment]
Hi @cryptogeek13 ,

thanks for your issue.
Currently the push to docker's hub are done "manually", with Github's workflow. I'm considering using a trigger linked to Wishthis repository, or otherwise setting up an automatic build every day.


I push last night, everything seems to be up to date (_release-candidate_), I compared with the last Wishthis's commit. 

You can update your container :
https://hub.docker.com/layers/hiob/wishthis/release-candidate/images/sha256-dd9a643168fe9fb62d4b5e7bac703cf285c3315122d508fc419a778d3abbe608?context=repo

**Comment by proud-nerd** [comment]
Thank you!

While that will fix my current caching issues, shouldn't the images build on the 04.10. still have included all changes up to that point?

**Comment by Hiobi** [comment]
Are you talking about this issue ? https://github.com/wishthis/wishthis/issues/108

You mention version 04.10, what exactly are you talking about?

I only checked the presence of the last commit in the container files. The rest should be there. ☺️

**Comment by proud-nerd** [comment]
No, my point was the discrepancy between the date the image was pushed and the date of the last change it included.

At that time an image was pushed on 04.10., but it did only include commits from the wishlist release-candidate branch up to the 24.09. Commits from 25.09. and 27.09. where missing.

That being said, I don't know how this could be replicated or investigated, since there are no versions on docker hub that could be pulled to investigate. So I'm fine with this issue being closed and  reopen again if it occurs again. In that case I'll keep that image then.
